### ISSUE TITLE
ValueError: need at least one array to stack

### ISSUE THREAD

**Issue by Gaozihui** [zju3dv/LoG#15]
The example data does not align with the default config/example/test/dataset.yml

> [Config] merge from parent file: config/example/test/dataset.yml
[Config] merge from parent file: config/example/test/level_of_gaussian.yml
[Config] merge from parent file: config/example/test/stage_8_4.yml
Key is not in the template: split
[Config] replace key $root
[Config] replace key $scale3d
[Config] replace key $root
[Config] replace key $scale3d
[Config] replace key $PLYNAME
[Config] replace key $PLYNAME
[Config] replace key $PLYNAME
[Config] replace key $PLYNAME
[Config] replace key $xyz_scale
[Config] replace key $scale3d
[Config] replace key $PLYNAME
[Config] replace key $xyz_scale
[Config] replace key $max_steps
[Config] replace key $dataset
[Config] replace key $RGB_RENDER_L1_SSIM
[Config] replace key $NAIVE_STAGE
[Config] replace key $val_dataset
Using GPUs: 0
Write to output/example/test/log
Using /home/gzh/.cache/torch_extensions/py310_cu118 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/gzh/.cache/torch_extensions/py310_cu118/compute_radius/build.ninja...
Building extension module compute_radius...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module compute_radius...
[data/feicuiwan_sample_folder/sparse/0/sparse.npz] mean: -0.022, 2.020, 2.000
[data/feicuiwan_sample_folder/sparse/0/sparse.npz] std: 1.220, 1.035, 0.988
[data/feicuiwan_sample_folder/sparse/0/sparse.npz] sigma=1 60490/157773
bounds: [[-1.243, 0.985, 1.012], [1.198, 3.055, 2.988]]
[data/feicuiwan_sample_folder/sparse/0/sparse.npz] sigma=2 146807/157773
bounds: [[-2.463, -0.050, 0.024], [2.418, 4.090, 3.976]]
[data/feicuiwan_sample_folder/sparse/0/sparse.npz] sigma=3 157746/157773
bounds: [[-3.683, -1.085, -0.963], [3.638, 5.125, 4.964]]
[data/feicuiwan_sample_folder/sparse/0/sparse.npz] z_min: -1.674, z_max: 25.249
[Load PLY] load from ply: data/feicuiwan_sample_folder/sparse/0/sparse.npz
[Load PLY] min: [-25.73409444  -1.02080217  -1.67376676], max: [ 3.12257119 16.14579238 25.24853616]
[Load PLY] scale: 0.0003, 22.9964, mean = 0.0139
[GaussianPoint] scales: [0.0003~0.0139~22.9964]
[GaussianPoint] -> scales: [0.0035~0.0133~0.0556]
>>> Code 213 files has been copied to output/example/test/log/code_backup_20240514-193851
[ImageDataset] set scales: [1, 2, 4, 8], crop size: [-1, -1]
[ImageDataset] cache dir: /mnt/nas/share2/home/gzh/code/LoG/data/feicuiwan_sample_folder/cache
[ImageDataset] offset: [0.0284959  0.01992458 0.01470781], radius: 6.153295601864254
[ImageDataset] init dataset with 180 images
Base iteration: 200
[ImageDataset] set scales: [4], crop size: [-1, -1]
[ImageDataset] cache dir: /mnt/nas/share2/home/gzh/code/LoG/data/feicuiwan_sample_folder/cache_val
Loaded 180 cameras from /mnt/nas/share2/home/gzh/code/LoG/data/feicuiwan_sample_folder/sparse/0
scale3d = 1.0
[ImageDataset] init camera y
Not exists: /mnt/nas/share2/home/gzh/code/LoG/data/feicuiwan_sample_folder/images/y/8y01073.JPG
[ImageDataset] init camera q
Not exists: /mnt/nas/share2/home/gzh/code/LoG/data/feicuiwan_sample_folder/images/q/8q01283.JPG
[ImageDataset] init camera h
Not exists: /mnt/nas/share2/home/gzh/code/LoG/data/feicuiwan_sample_folder/images/h/8h01559.JPG
Not exists: /mnt/nas/share2/home/gzh/code/LoG/data/feicuiwan_sample_folder/images/y/8y01755.JPG
Not exists: /mnt/nas/share2/home/gzh/code/LoG/data/feicuiwan_sample_folder/images/q/8q01543.JPG
Not exists: /mnt/nas/share2/home/gzh/code/LoG/data/feicuiwan_sample_folder/images/q/8q01330.JPG
[ImageDataset] undistort and scale 0 images 
0it [00:00, ?it/s]
write cache to  /mnt/nas/share2/home/gzh/code/LoG/data/feicuiwan_sample_folder/cache_val.pkl
[ImageDataset] set scales: [4], crop size: [-1, -1]
[ImageDataset] cache dir: /mnt/nas/share2/home/gzh/code/LoG/data/feicuiwan_sample_folder/cache_val
Traceback (most recent call last):
  File "/mnt/nas/share/home/gzh/anaconda3/envs/LoG/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/mnt/nas/share/home/gzh/anaconda3/envs/LoG/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/gzh/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/gzh/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/gzh/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/gzh/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/gzh/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/gzh/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "apps/train.py", line 183, in <module>
    main()
  File "apps/train.py", line 163, in main
    trainer = Trainer(cfg, model, renderer, logdir=outdir)
  File "/mnt/nas/share2/home/gzh/code/LoG/LoG/utils/trainer.py", line 56, in __init__
    self.check_val()
  File "/mnt/nas/share2/home/gzh/code/LoG/LoG/utils/trainer.py", line 65, in check_val
    dataset = load_object(self.cfg.val.dataset.module, self.cfg.val.dataset.args)
  File "/mnt/nas/share2/home/gzh/code/LoG/LoG/utils/config.py", line 61, in load_object
    obj = getattr(module, name)(**extra_args, **module_args)
  File "/mnt/nas/share2/home/gzh/code/LoG/LoG/dataset/colmap.py", line 159, in __init__
    centers = np.stack([-info['camera']['R'].T @ info['camera']['T'] for info in infos], axis=0)
  File "/mnt/nas/share/home/gzh/anaconda3/envs/LoG/lib/python3.10/site-packages/numpy/core/shape_base.py", line 445, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack

**Comment by chingswy** [comment]
Hello, if you're having issues with the smaller dataset, please download the full dataset and try again.

**Comment by renaissanceee** [comment]
I think it's because the **_cache_val.pkl_** is missing in small dataset.
