### ISSUE TITLE
compute_radius

### ISSUE THREAD

**Issue by KL-2** [zju3dv/LoG#22]
Great Job!
when I try to run the commend : python LoG/cuda/compute_radius.py
code get stuck for a long time.
according to the other issues,the correct output should be :
Using /home/user/.cache/torch_extensions/py310_cu118 as PyTorch extensions root...
Detected CUDA files, patching ldflags

...

while my output is just
Using /home/user/.cache/torch_extensions/py310_cu118 as PyTorch extensions root...
then stuck

may I ask whether I didnot wait enough time and how long should I wait 
or something otherwhere is wrong.
Thanks for your reply.

**Comment by KL-2** [comment]
when Ctrl+C
Traceback (most recent call last):
  File "/home/user/software/LoG/apps/train.py", line 183, in <module>
    main()
  File "/home/user/software/LoG/apps/train.py", line 148, in main
    model = load_object(cfg.model.module, cfg.model.args)
  File "/home/user/software/LoG/LoG/utils/config.py", line 59, in load_object
    module = importlib.import_module(module_path)
  File "/home/user/anaconda3/envs/LoG/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/user/software/LoG/LoG/model/level_of_gaussian.py", line 11, in <module>
    from ..cuda.compute_radius import compute_radius_module
  File "/home/user/software/LoG/LoG/cuda/compute_radius.py", line 3, in <module>
    compute_radius_module = load(
  File "/home/user/anaconda3/envs/LoG/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/home/user/anaconda3/envs/LoG/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1523, in _jit_compile
    baton.wait()
  File "/home/user/anaconda3/envs/LoG/lib/python3.10/site-packages/torch/utils/file_baton.py", line 42, in wait
    time.sleep(self.wait_seconds)
KeyboardInterrupt
all dependiences are the same as the install.md
