### ISSUE TITLE
training on custom data

### ISSUE THREAD

**Issue by shankar-anantak** [zju3dv/LoG#5]
Hello,

I am trying to train the model on my custom data captured from a phone camera. Pre-processed fine w/ COLMAP, however, when i try to train the model:

```
python3 apps/train.py --cfg config/example/test/train.yml split train
```

```
[Config] merge from parent file: config/example/test/dataset.yml
[Config] merge from parent file: config/example/test/level_of_gaussian.yml
[Config] merge from parent file: config/example/test/stage_8_4.yml
Key is not in the template: split
[Config] replace key $root
[Config] replace key $scale3d
[Config] replace key $root
[Config] replace key $scale3d
[Config] replace key $PLYNAME
[Config] replace key $PLYNAME
[Config] replace key $PLYNAME
[Config] replace key $xyz_scale
[Config] replace key $scale3d
[Config] replace key $PLYNAME
[Config] replace key $xyz_scale
[Config] replace key $max_steps
[Config] replace key $dataset
[Config] replace key $RGB_RENDER_L1_SSIM
[Config] replace key $NAIVE_STAGE
[Config] replace key $val_dataset
Using GPUs: 0
Write to output/example/test/log
[/home/dev/dev/data/2023-12-18_15.06.36/sparse/0/sparse.npz] mean: -0.276, 0.500, -1.018
[/home/dev/dev/data/2023-12-18_15.06.36/sparse/0/sparse.npz] std: 1.480, 1.085, 3.215
[/home/dev/dev/data/2023-12-18_15.06.36/sparse/0/sparse.npz] sigma=1 49864/125443
bounds: [[-1.756, -0.584, -4.233], [1.204, 1.585, 2.197]]
[/home/dev/dev/data/2023-12-18_15.06.36/sparse/0/sparse.npz] sigma=2 114402/125443
bounds: [[-3.236, -1.669, -7.449], [2.683, 2.670, 5.412]]
[/home/dev/dev/data/2023-12-18_15.06.36/sparse/0/sparse.npz] sigma=3 122545/125443
bounds: [[-4.715, -2.754, -10.664], [4.163, 3.755, 8.627]]
[/home/dev/dev/data/2023-12-18_15.06.36/sparse/0/sparse.npz] z_min: -53.713, z_max: 23.659
[Load PLY] load from ply: /home/dev/dev/data/2023-12-18_15.06.36/sparse/0/sparse.npz
[Load PLY] min: [-10.02181557 -10.31714249 -53.71318683], max: [18.95321076 24.50246681 23.65868778]
[Load PLY] scale: 0.0003, 22.6722, mean = 0.0294
[GaussianPoint] scales: [0.0003~0.0294~22.6722]
[GaussianPoint] -> scales: [0.0074~0.0255~0.1176]
>>> Code 3062 files has been copied to output/example/test/log/code_backup_20240501-190914
[ImageDataset] set scales: [1, 2, 4, 8], crop size: [-1, -1]
[ImageDataset] cache dir: /home/dev/dev/data/2023-12-18_15.06.36/cache
Traceback (most recent call last):
  File "/home/dev/dev/LoG/apps/train.py", line 157, in <module>
    main()
  File "/home/dev/dev/LoG/apps/train.py", line 130, in main
    dataset = load_object(cfg.train.dataset.module, cfg.train.dataset.args)
  File "/home/dev/dev/LoG/LoG/utils/config.py", line 61, in load_object
    obj = getattr(module, name)(**extra_args, **module_args)
  File "/home/dev/dev/LoG/LoG/dataset/colmap.py", line 159, in __init__
    centers = np.stack([-info['camera']['R'].T @ info['camera']['T'] for info in infos], axis=0)
  File "/home/dev/miniconda3/envs/LoG/lib/python3.10/site-packages/numpy/core/shape_base.py", line 445, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack
```

I modified the dataset path in config/example/test/dataset.yml to match my input data path.

Are there further steps required for custom data? Your advice would be appreciated. 

Thanks

**Comment by chingswy** [comment]
This issue arises from the validation settings. You can resolve it by deleting the `val:` and its related properties in the `config/example/test/train.yml` file.

**Comment by chingswy** [comment]
It seems that the dataset can't find any camera parameters. Can you show you folder structure?

**Comment by shankar-anantak** [comment]
Sure, 

(LoG) dev@instance-20240430-202938:~/dev/LoG$ ls
LoG  LoG.egg-info  README.md  apps  assets  config  docs  output  requirements.txt  setup.py  submodules
(LoG) dev@instance-20240430-202938:~/dev/LoG$ ls ../data/2023-12-18_15.06.36/sparse/0/
cameras.bin  extri.yml  images.bin  intri.yml  points3D.bin  project.ini  sparse.npz  sparse.ply
(LoG) dev@instance-20240430-202938:~/dev/LoG$ 

My LoG root: /home/dev/dev/LoG
My COLMAP output: /home/dev/dev/data/2023-12-18_15.06.36/sparse/0

Paths in the dataset.yml:

root: /home/dev/dev/data/2023-12-18_15.06.36
PLYNAME: /home/dev/dev/data/2023-12-18_15.06.36/sparse/0/sparse.npz

Your help is greatly appreciated

**Comment by chingswy** [comment]
You can try to remove `data/2023-12-18_15.06.36/cache` and `data/2023-12-18_15.06.36/cache.pkl` and retry.

**Comment by chingswy** [comment]
Hello, your image extension is .jpg instead of .JPG. You should modify this in dataset.yml

**Comment by shankar-anantak** [comment]
Thank you for helping me resolve that silly mistake. Unfortunately, I have a new issue:

```
write cache to  /home/dev/dev/LoG/data/2023-12-18_15.06.36/cache.pkl
[ImageDataset] offset: [ 0.00241288  0.02408803 -0.06257018], radius: 6.018952590965555
[ImageDataset] init dataset with 677 images
[ImageDataset] set scale 4, crop_size: [-1, -1], downsample_scale: 1
initialize the model: 100%|██████████████████████████████████████████████████████████████████████████████| 677/677 [00:01<00:00, 557.18it/s]
[LoG] minimum scales: [0.0004~0.0027~0.0818]
Traceback (most recent call last):
  File "/home/dev/dev/LoG/apps/train.py", line 157, in <module>
    main()
  File "/home/dev/dev/LoG/apps/train.py", line 139, in main
    trainer.init(dataset)
  File "/home/dev/dev/LoG/LoG/utils/trainer.py", line 177, in init
    self.model.at_init_final()
  File "/home/dev/dev/LoG/LoG/model/level_of_gaussian.py", line 326, in at_init_final
    self.counter.radius3d_max.fill_(self.gaussian.xyz_scale * 0.2)
TypeError: can't multiply sequence by non-int of type 'float'
```

Again, your assistance is truly appreciated

**Comment by chingswy** [comment]
You can check `self.gaussian.xyz_scale` in this line.

**Comment by luoww1992** [comment]
@chingswy 
i use a dataset from internet, this my dataset:
链接：https://pan.baidu.com/s/1PMnA-ibSCqNEmvuCb05cPA 
提取码：2ttz 
--来自百度网盘超级会员V6的分享
i change the dataset dir and delele args val in train.yaml 
and delete the pkl file and cache fold before runing.
then training error:
```
[ImageDataset] undistort and scale 107 images
100%|████████████████████████████████████████████████████████████████████████████████| 107/107 [00:35<00:00,  2.99it/s]
write cache to  D:\GS_Pro\LoG\data\boli\cache.pkl
[ImageDataset] offset: [3.07092454e-02 2.35425679e-05 2.92656670e-02], radius: 5.4546816443016715
[ImageDataset] init dataset with 107 images
Base iteration: 200
[ImageDataset] set scale 1, crop_size: [-1, -1], downsample_scale: 1
initialize the model: 100%|██████████████████████████████████████████████████████████| 107/107 [00:17<00:00,  6.20it/s]
[LoG] minimum scales: [0.0002~0.0006~0.0044]
[Corrector] init view correction: 107
[ImageDataset] set partial indices 107
quick view:  10%|███████                                                              | 11/107 [00:06<00:59,  1.63it/s]
[ImageDataset] set partial indices 107
> Run stage: init. 30000 iterations
[ImageDataset] set scale 8, crop_size: [-1, -1], downsample_scale: 1
[SparseOptimizer] xyz_scale: 1.0, steps: 150000, lr 0.00016->1.6e-06
[SparseOptimizer] scaling: 0.005 -> 0.005
[LoG] optimizer setup: max steps = 150000
[Counter] reset counter -> 96007
[Corrector] view correction optimizer setup 0.001
Traceback (most recent call last):
  File "D:\GS_Pro\LoG\apps\train.py", line 169, in <module>
    main()
  File "D:\GS_Pro\LoG\apps\train.py", line 166, in main
    trainer.fit(dataset)
  File "d:\gs_pro\log\LoG\utils\trainer.py", line 487, in fit
    for iteration, data in enumerate(trainloader):
  File "G:\miniconda3\envs\log\lib\site-packages\torch\utils\data\dataloader.py", line 439, in __iter__
    return self._get_iterator()
  File "G:\miniconda3\envs\log\lib\site-packages\torch\utils\data\dataloader.py", line 387, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "G:\miniconda3\envs\log\lib\site-packages\torch\utils\data\dataloader.py", line 1040, in __init__
    w.start()
  File "G:\miniconda3\envs\log\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "G:\miniconda3\envs\log\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "G:\miniconda3\envs\log\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "G:\miniconda3\envs\log\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "G:\miniconda3\envs\log\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'Trainer.train_loader.<locals>.worker_init_fn'

(log) D:\GS_Pro\LoG>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "G:\miniconda3\envs\log\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "G:\miniconda3\envs\log\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
```
i looks like the dataset loads wrong.

**Comment by chingswy** [comment]
Hello, I am able to load your data and train normally on my computer, but I only have a Linux testing environment. Your issue might be related to Windows or a specific problem with PyTorch.

**Comment by jorenmichels** [comment]
> @chingswy i use a dataset from internet, this my dataset: 链接：https://pan.baidu.com/s/1PMnA-ibSCqNEmvuCb05cPA 提取码：2ttz --来自百度网盘超级会员V6的分享 i change the dataset dir and delete args val in train.yaml and delete the pkl file and cache fold before runing. then training error:
> 
> ```
> [ImageDataset] undistort and scale 107 images
> 100%|████████████████████████████████████████████████████████████████████████████████| 107/107 [00:35<00:00,  2.99it/s]
> write cache to  D:\GS_Pro\LoG\data\boli\cache.pkl
> [ImageDataset] offset: [3.07092454e-02 2.35425679e-05 2.92656670e-02], radius: 5.4546816443016715
> [ImageDataset] init dataset with 107 images
> Base iteration: 200
> [ImageDataset] set scale 1, crop_size: [-1, -1], downsample_scale: 1
> initialize the model: 100%|██████████████████████████████████████████████████████████| 107/107 [00:17<00:00,  6.20it/s]
> [LoG] minimum scales: [0.0002~0.0006~0.0044]
> [Corrector] init view correction: 107
> [ImageDataset] set partial indices 107
> quick view:  10%|███████                                                              | 11/107 [00:06<00:59,  1.63it/s]
> [ImageDataset] set partial indices 107
> > Run stage: init. 30000 iterations
> [ImageDataset] set scale 8, crop_size: [-1, -1], downsample_scale: 1
> [SparseOptimizer] xyz_scale: 1.0, steps: 150000, lr 0.00016->1.6e-06
> [SparseOptimizer] scaling: 0.005 -> 0.005
> [LoG] optimizer setup: max steps = 150000
> [Counter] reset counter -> 96007
> [Corrector] view correction optimizer setup 0.001
> Traceback (most recent call last):
>   File "D:\GS_Pro\LoG\apps\train.py", line 169, in <module>
>     main()
>   File "D:\GS_Pro\LoG\apps\train.py", line 166, in main
>     trainer.fit(dataset)
>   File "d:\gs_pro\log\LoG\utils\trainer.py", line 487, in fit
>     for iteration, data in enumerate(trainloader):
>   File "G:\miniconda3\envs\log\lib\site-packages\torch\utils\data\dataloader.py", line 439, in __iter__
>     return self._get_iterator()
>   File "G:\miniconda3\envs\log\lib\site-packages\torch\utils\data\dataloader.py", line 387, in _get_iterator
>     return _MultiProcessingDataLoaderIter(self)
>   File "G:\miniconda3\envs\log\lib\site-packages\torch\utils\data\dataloader.py", line 1040, in __init__
>     w.start()
>   File "G:\miniconda3\envs\log\lib\multiprocessing\process.py", line 121, in start
>     self._popen = self._Popen(self)
>   File "G:\miniconda3\envs\log\lib\multiprocessing\context.py", line 224, in _Popen
>     return _default_context.get_context().Process._Popen(process_obj)
>   File "G:\miniconda3\envs\log\lib\multiprocessing\context.py", line 327, in _Popen
>     return Popen(process_obj)
>   File "G:\miniconda3\envs\log\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
>     reduction.dump(process_obj, to_child)
>   File "G:\miniconda3\envs\log\lib\multiprocessing\reduction.py", line 60, in dump
>     ForkingPickler(file, protocol).dump(obj)
> AttributeError: Can't pickle local object 'Trainer.train_loader.<locals>.worker_init_fn'
> 
> (log) D:\GS_Pro\LoG>Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "G:\miniconda3\envs\log\lib\multiprocessing\spawn.py", line 116, in spawn_main
>     exitcode = _main(fd, parent_sentinel)
>   File "G:\miniconda3\envs\log\lib\multiprocessing\spawn.py", line 126, in _main
>     self = reduction.pickle.load(from_parent)
> EOFError: Ran out of input
> ```
> 
> i looks like the dataset loads wrong.

There are a lot of places in the code where they specify the amount of cpu workers (num_workers). If you set all of them to 1, it should work on windows.
